[package]
name = "ntex-router"
version = "0.5.3"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Path router"
keywords = ["ntex"]
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-router/"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "ntex_router"
path = "src/lib.rs"

[features]
default = ["http"]

[dependencies]
serde = "1.0"
ntex-bytes = "0.1.21"
log = "0.4"
http = { version = "1", optional = true }
regex = { version = "1.9", default-features = false, features = ["std"] }

[dev-dependencies]
http = "1"
serde_derive = "1.0"
